apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthapp-eta-deploy
  labels:
    app: healthapp-eta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthapp-eta-app
  template:
    metadata:
      labels:
        app: healthapp-eta-app
    spec:
      containers:
      - name: healthapp-eta-container
        image: yash1999v/healthapp
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthapp-eta-np-service
  labels:
    app: healthapp-eta-app
spec:
  selector:
    app: healthapp-eta-app

  type: NodePort
  ports:
  - nodePort: 31032    
    port: 8082
    targetPort: 8082
